# Site settings
title: Tech Blog - jQN.io
header-img: img/home-bg.jpg
email: joaquin_guardado@icloud.com
description: "Tech talk about awesome Node.js, the MEAN stack, Drupal and the LAMP stack."
baseurl: " "
url: ""
# twitter_username: SBootstrap
github_username:  jqn
# facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
